### PR TITLE
Update metapackage

### PR DESCRIPTION
**Pull request by loid345**
Update metapackage Inventory Management and Adobe Stock Integration

### CODE REVIEW

**Comment by magenx** [comment]
this file is not in use
if you look inside magento installation taken from here
https://github.com/magenx/Magento-2

agree this is some hackish workaround, but magento is dependency monster anyway

**Review by loid345 — COMMENTED** [review]
Fix inventory metapackage

**Comment by loid345** [comment]
This is the correct way to remove modules with dependencies.

**Comment by magenx** [comment]
actually back to composer replace,
but removing everything , just in case ;)

**Pull request closed without merging**
